### ISSUE TITLE
'List' object has no attribute 'keys'

### ISSUE THREAD

**Issue by chandelures** [gesy17/TGBully#1]
First, thanks your nice work.
But I run `Instagram_code.ipynb`, in "Load user history data" part, line 24

```python
# Load user history data
userhistory=[]
pattern = re.compile(r'^userID:.*\susername:.*\scommentText:.*$') 
for filename in os.listdir(normalUser_path):
    with open(normalUser_path+filename,'r',encoding="utf8") as f:
        lines=f.readlines()
        for line in lines:
            sub = pattern.search(line) 
            try:
                sub.group()
                userhistory.append(line)
            except:
                pass
for filename in os.listdir(commonUser_path):
    with open(commonUser_path+filename,'r',encoding="utf8") as f:
        lines=f.readlines()
        for line in lines:
            sub = pattern.search(line) 
            try:
                sub.group()
                userhistory.append(line)
            except:
                pass
for person in userhistory.keys():
    for i in range(len(userhistory[person])):
        userhistory[person][i]= word_tokenize(userhistory[person][i].lower())
        if userhistory[person][i][0]=='@':
            userhistory[person][i]=userhistory[person][i][2:]
```

and it throw the error look like

```shell
---> 24 for person in userhistory.keys():
     25     for i in range(len(userhistory[person])):
     26         userhistory[person][i]= word_tokenize(userhistory[person][i].lower())

AttributeError: 'list' object has no attribute 'keys'
```

in previous code, `userhistory` is a list object rather than a dict object. 
is there something missing or something wrong in the code?

**Comment by gesy17** [comment]
Hi,

Thanks for your interest in this work! Sorry for my mistake, the `userhistory` should be a dictionary where the key is `userID` and value being the `commentText`. 

Best,
Suyu

**Comment by chandelures** [comment]
Thanks for your response, 

I tried to fix it and the following code may be helpful for someone having the same question,

```python
# Load user history data
userhistory={}
pattern = re.compile(r'^userID:.*\susername:.*\scommentText:.*$') 
for filename in os.listdir(normalUser_path):
    with open(normalUser_path+filename,'r',encoding="utf8") as f:
        lines=f.readlines()
        for line in lines:
            if pattern.search(line):
                userID = re.findall('userID:(.*) username', line)[0]
                commentText = re.findall('commentText:(.*)', line)[0]
                if userID not in userhistory:
                    userhistory[userID] = []
                userhistory[userID].append(commentText)
for filename in os.listdir(commonUser_path):
    with open(commonUser_path+filename,'r',encoding="utf8") as f:
        lines=f.readlines()
        for line in lines:
            if pattern.search(line):
                userID = re.findall('userID:(.*) username', line)[0]
                commentText = re.findall('commentText:(.*)', line)[0]
                if userID not in userhistory:
                    userhistory[userID] = []
                userhistory[userID].append(commentText)

for person in userhistory.keys():
    for i in range(len(userhistory[person])):
        if userhistory[person][i] and userhistory[person][i][0]=='@':
            userhistory[person][i]=userhistory[person][i][1:]
        userhistory[person][i] = userhistory[person][i].replace('@', '')
```

**Comment by 812559558** [comment]
遇到了同样的问题，好在大佬解决了

**Comment by 812559558** [comment]
这个代码真的能运行吗，改完一处，后面还是有各种各样的error

**Comment by 812559558** [comment]
> Thanks for your response,
> 
> I tried to fix it and the following code may be helpful for someone having the same question,
> 
> ```python
> # Load user history data
> userhistory={}
> pattern = re.compile(r'^userID:.*\susername:.*\scommentText:.*$') 
> for filename in os.listdir(normalUser_path):
>     with open(normalUser_path+filename,'r',encoding="utf8") as f:
>         lines=f.readlines()
>         for line in lines:
>             if pattern.search(line):
>                 userID = re.findall('userID:(.*) username', line)[0]
>                 commentText = re.findall('commentText:(.*)', line)[0]
>                 if userID not in userhistory:
>                     userhistory[userID] = []
>                 userhistory[userID].append(commentText)
> for filename in os.listdir(commonUser_path):
>     with open(commonUser_path+filename,'r',encoding="utf8") as f:
>         lines=f.readlines()
>         for line in lines:
>             if pattern.search(line):
>                 userID = re.findall('userID:(.*) username', line)[0]
>                 commentText = re.findall('commentText:(.*)', line)[0]
>                 if userID not in userhistory:
>                     userhistory[userID] = []
>                 userhistory[userID].append(commentText)
> 
> for person in userhistory.keys():
>     for i in range(len(userhistory[person])):
>         if userhistory[person][i] and userhistory[person][i][0]=='@':
>             userhistory[person][i]=userhistory[person][i][1:]
>         userhistory[person][i] = userhistory[person][i].replace('@', '')
> ```

老哥你后面跑通了吗
